"""Context-limited word embeddings from Llama-3-8B.

For a context window of K words, every word is embedded with its tokens allowed
to attend only to the tokens of the K preceding words (the word itself
included) and to the beginning-of-sequence token, under the usual causal
constraint. This is done with a custom 2D attention mask, so that many target
words are processed in one forward pass over a chunk of the transcript.

The position ids of the full transcript are kept (passed explicitly), so
truncating the context changes what the model can see without changing the
rotary positional encoding. The K-word embeddings are therefore directly
comparable to the full-context ones.

The hidden state of each requested layer is mean-pooled over the sub-tokens of
each word. The model runs in bfloat16 on a single GPU.

Llama-3 is a gated model: accept its licence on Hugging Face and set HF_TOKEN.

Input:
  <BIDS_ROOT>/stimuli/podcast_transcript.csv

Output:
  <data dir>/embeddings/llama3/context_windows/layer_<L>/embeddings/
      llama3_layer_<L>_window_<K>_word_embeddings.npy       (n_words, 4096)

Usage:
  python mind_in_context/preprocessing/generate_llama3_embeddings_context_windows.py
  python mind_in_context/preprocessing/generate_llama3_embeddings_context_windows.py
      --context-windows 2,3,4,5 --layers 5,10,15,20,25,30
"""

from __future__ import annotations

import argparse
import json
import os
import gc
import sys
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

import numpy as np
import pandas as pd
import torch
from numpy.lib.format import open_memmap
from tqdm import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from mind_in_context.lib.io import EMBEDDINGS_DIR, PODCAST_TRANSCRIPT_CSV  # noqa: E402

# --------------------------------------------------------------------------------------
# Paths & Configuration
# --------------------------------------------------------------------------------------

TRANSCRIPT_CSV: Path = PODCAST_TRANSCRIPT_CSV
BASE_RESULTS_DIR: Path = EMBEDDINGS_DIR / "llama3" / "context_windows"

MODEL_NAME = "meta-llama/Meta-Llama-3-8B"

# Indices into the Hugging Face hidden_states tuple: 0 is the token-embedding
# output, i is the output of transformer layer i - 1. Override with --layers.
TARGET_LAYERS = list(range(0, 33, 5))

# Context windows generated by default (number of words, target included). The
# full narrative is produced by generate_llama3_embeddings_full_context.py.
DEFAULT_CONTEXT_WINDOWS: Tuple[int, ...] = tuple(range(1, 21))
TARGET_SEQ_LEN_LIMIT = 1000
INCLUDE_FULL_CONTEXT_WINDOW = False

# --------------------------------------------------------------------------------------
# Word-embedding mode (context=0) + first layers
# --------------------------------------------------------------------------------------
#
# Optional: embed each word with no context at all, for the first layers only.
# Layer indices are hidden_states indices:
#   - layer_index=0  => token embedding output (pre-transformer)
#   - layer_index=1  => transformer layer 0 output
#   - layer_index=2  => transformer layer 1 output
# Off by default; not used for the paper.
WORD_EMBEDDING_MODE = False
WORD_EMBEDDING_WINDOWS: Tuple[int, ...] = (0,)  # window_size=0 means "current word only" (special-cased)
WORD_EMBEDDING_LAYER_INDICES: Tuple[int, ...] = (0, 1, 2)

# --------------------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------------------

def ensure_directories(results_dir: Path, embeddings_dir: Path) -> None:
    os.makedirs(results_dir, exist_ok=True)
    os.makedirs(embeddings_dir, exist_ok=True)

def precompute_transcript_tokens(words: list[str], tokenizer) -> Tuple[torch.Tensor, np.ndarray, np.ndarray]:
    """Tokenize entire text and map word indices to token ranges."""
    enc = tokenizer(words, is_split_into_words=True, add_special_tokens=False)

    raw_input_ids = enc['input_ids']

    # Handle BOS
    # Llama 3 usually has BOS token (128000). Check tokenizer.bos_token_id.
    bos_id = tokenizer.bos_token_id
    offset = 0
    if bos_id is not None:
        full_input_ids = torch.tensor([bos_id] + raw_input_ids, dtype=torch.long)
        offset = 1
    else:
        full_input_ids = torch.tensor(raw_input_ids, dtype=torch.long)

    word_ids = enc.word_ids()
    word_ids_arr = np.array(word_ids)

    # Vectorized word boundaries
    _, unique_indices = np.unique(word_ids_arr, return_index=True)

    starts = unique_indices + offset
    ends = np.append(starts[1:], len(word_ids_arr) + offset)

    return full_input_ids, starts, ends

def generate_embeddings_fast(
    window_size: int,
    full_input_ids: torch.Tensor,
    starts: np.ndarray, # global starts
    ends: np.ndarray,   # global ends
    n_words: int,
    model,
    tokenizer,
    layer_indices: List[int],
    device: torch.device,
    hidden_size: int,
    base_results_dir: Path,
    skip_existing: bool = False
) -> Dict[int, str]:

    # Setup Paths
    layer_paths = {}
    all_exist = True
    for layer_idx in layer_indices:
        layer_results_dir = base_results_dir / f"layer_{layer_idx}"
        embeddings_dir = layer_results_dir / "embeddings"
        ensure_directories(layer_results_dir, embeddings_dir)
        out_path = embeddings_dir / f"llama3_layer_{layer_idx}_window_{window_size}_word_embeddings.npy"
        layer_paths[layer_idx] = str(out_path)
        if not out_path.exists():
            all_exist = False

    if skip_existing and all_exist:
        print(f"Skipping window {window_size} (all layer files exist)")
        return layer_paths

    # Memmaps
    memmaps = {}
    for layer_idx, path in layer_paths.items():
        memmaps[layer_idx] = open_memmap(path, dtype="float32", mode="w+", shape=(n_words, hidden_size))

    # Determine Stride and Chunk Size
    tokens_per_word_est = 1.5
    limit_words = int(TARGET_SEQ_LEN_LIMIT / tokens_per_word_est)

    stride_words = max(10, limit_words - max(1, window_size))
    if stride_words < 1:
        stride_words = 50 # Fallback for very large windows

    # Ensure BOS
    bos_token = full_input_ids[0:1] # Assuming 0 is BOS
    has_global_bos = (starts[0] == 1)

    # Treat window_size=0 as "word only" (no context). Internally this behaves like a 1-word window.
    effective_window = 1 if window_size == 0 else window_size
    if window_size == 0:
        print("Note: window_size=0 requested -> using effective_window=1 (current word only).")

    # Main Loop over Target Words
    progress = tqdm(range(0, n_words, stride_words), desc=f"Win {window_size}, Stride {stride_words}")

    for start_word_idx in progress:
        end_word_idx = min(start_word_idx + stride_words, n_words)

        # Determine context range
        context_start_word_idx = max(0, start_word_idx - effective_window + 1)

        chunk_start_token = starts[context_start_word_idx]
        if context_start_word_idx == 0 and has_global_bos:
            chunk_start_token = 0 # Include BOS naturally

        chunk_end_token = ends[end_word_idx - 1] # End of the last target word

        chunk_input_ids = full_input_ids[chunk_start_token : chunk_end_token]

        # Prepend BOS if needed
        prepended_bos = False
        if context_start_word_idx > 0 and has_global_bos:
            chunk_input_ids = torch.cat([bos_token, chunk_input_ids], dim=0)
            prepended_bos = True

        seq_len = len(chunk_input_ids)

        # Create Attention Mask
        # Optimization: Create 'word_ids_seq' tensor for the chunk
        word_ids_seq = torch.full((seq_len,), -1, dtype=torch.long)

        current_offset = 1 if prepended_bos else 0
        global_start_offset = chunk_start_token

        relevant_words = range(context_start_word_idx, end_word_idx)
        for w_idx in relevant_words:
            s = starts[w_idx] - global_start_offset + current_offset
            e = ends[w_idx] - global_start_offset + current_offset
            if s < seq_len and e <= seq_len:
                word_ids_seq[s:e] = w_idx

        # Mask Construction
        w_ids_i = word_ids_seq.unsqueeze(1)
        w_ids_j = word_ids_seq.unsqueeze(0)

        attn_mask = (w_ids_j <= w_ids_i) # Causal
        is_bos_j = (w_ids_j == -1)
        window_cond = (w_ids_j >= (w_ids_i - effective_window + 1))

        final_mask_bool = attn_mask & (is_bos_j | window_cond)
        final_mask_tensor = final_mask_bool.to(device)

        # Prepare Batch
        input_ids_gpu = chunk_input_ids.unsqueeze(0).to(device)
        # 4D Mask for broadcasting (Batch, 1, Seq, Seq)
        mask_gpu = final_mask_tensor.unsqueeze(0).unsqueeze(1).to(device)

        # --- POSITIONAL ENCODINGS FIX ---
        # Construct position_ids matching global positions
        base_positions = torch.arange(chunk_start_token, chunk_end_token, dtype=torch.long)
        if prepended_bos:
            bos_pos = torch.tensor([0], dtype=torch.long) # BOS is always at 0
            position_ids = torch.cat([bos_pos, base_positions], dim=0)
        else:
            position_ids = base_positions

        position_ids_gpu = position_ids.unsqueeze(0).to(device)
        # --------------------------------

        with torch.inference_mode():
             outputs = model(
                input_ids=input_ids_gpu,
                attention_mask=mask_gpu,
                position_ids=position_ids_gpu, # Crucial for RoPE consistency
                output_hidden_states=True,
                use_cache=False
            )

        # Extract Embeddings
        for w_idx in range(start_word_idx, end_word_idx):
            s = starts[w_idx] - global_start_offset + current_offset
            e = ends[w_idx] - global_start_offset + current_offset

            if e > seq_len: continue

            for layer_idx in layer_indices:
                if layer_idx < len(outputs.hidden_states):
                    layer_h = outputs.hidden_states[layer_idx]
                    vec = layer_h[0, s:e, :].mean(dim=0)

                    # Convert to float32 before saving (Llama 3 often uses bfloat16)
                    vec_np = vec.float().detach().cpu().numpy().astype(np.float32)
                    memmaps[layer_idx][w_idx] = vec_np

        del outputs, input_ids_gpu, mask_gpu, position_ids_gpu
        torch.cuda.empty_cache()

    for m in memmaps.values():
        m.flush()

    return layer_paths

def parse_context_windows(
    raw_windows: Sequence[int] | None, full_len: int, auto_add_full_context: bool = True
) -> List[int]:
    windows = list(raw_windows or DEFAULT_CONTEXT_WINDOWS)

    # Allow using -1 as an explicit "full context" marker.
    windows = [full_len if int(w) == -1 else int(w) for w in windows]

    # Auto-add Full Context (Transcript Length)
    if auto_add_full_context and full_len not in windows:
        windows.append(full_len)

    # Allow window_size=0 ("word only") in addition to positive windows
    unique_sorted = sorted({int(w) for w in windows if int(w) >= 0})
    return unique_sorted

def assert_model_fully_on_cuda(model) -> None:
    hf_device_map = getattr(model, "hf_device_map", None)
    if hf_device_map is not None:
        non_cuda_entries = []
        for module_name, mapped_device in hf_device_map.items():
            mapped_device_str = str(mapped_device).lower()
            if mapped_device_str in {"cpu", "disk"}:
                non_cuda_entries.append((module_name, mapped_device))
                continue
            if isinstance(mapped_device, int):
                continue
            if not mapped_device_str.startswith("cuda"):
                non_cuda_entries.append((module_name, mapped_device))

        if non_cuda_entries:
            raise RuntimeError(
                "Model was not loaded fully on GPU. "
                f"Non-CUDA placements detected: {non_cuda_entries[:5]}"
            )

    non_cuda_params = [
        name for name, param in model.named_parameters() if param.device.type != "cuda"
    ]
    if non_cuda_params:
        raise RuntimeError(
            "Model parameters are not fully on GPU. "
            f"Example non-CUDA parameters: {non_cuda_params[:5]}"
        )

def main(
    context_windows: Sequence[int] | None = None,
    skip_existing: bool = False,
    full_context: bool = False,
) -> None:
    target_layers = TARGET_LAYERS

    print("--- FAST Llama-3-8B Embeddings Generation (Chunked + Positional Fix) ---")

    # Check for HF Token
    if "HF_TOKEN" not in os.environ:
        print("\nWARNING: HF_TOKEN environment variable not found. Llama 3 is gated.")

    # Init Model
    print(f"Loading Model: {MODEL_NAME}...")
    try:
        tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)
    except Exception as e:
        raise RuntimeError(f"Error loading tokenizer: {e}") from e

    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    if not torch.cuda.is_available():
        raise RuntimeError("CUDA is required. Refusing to continue on CPU.")

    try:
        model = AutoModelForCausalLM.from_pretrained(
            MODEL_NAME,
            torch_dtype=torch.bfloat16,
            device_map={"": 0},
            attn_implementation="sdpa",
        )
    except Exception as e:
        raise RuntimeError(
            "Error loading model on GPU. "
            "The run was stopped instead of falling back to CPU. "
            f"Original error: {e}"
        ) from e

    device = torch.device("cuda")
    assert_model_fully_on_cuda(model)
    model.eval()

    # Precompute
    print("Precomputing tokens...")
    df = pd.read_csv(TRANSCRIPT_CSV)
    words = df["word"].astype(str).tolist()
    n_words = len(words)
    full_input_ids, starts, ends = precompute_transcript_tokens(words, tokenizer)

    print(f"Transcript Length: {n_words} words, {len(full_input_ids)} tokens.")

    # Choose windows/layers
    if WORD_EMBEDDING_MODE:
        # Word-only context + first layers (embedding + layer0 + layer1)
        target_layers = list(WORD_EMBEDDING_LAYER_INDICES)
        raw_windows = WORD_EMBEDDING_WINDOWS if context_windows is None else context_windows
        windows = parse_context_windows(raw_windows, n_words, auto_add_full_context=False)
    else:
        # Default behavior: use requested windows (or defaults) + auto-add full length
        windows = parse_context_windows(
            context_windows,
            n_words,
            auto_add_full_context=bool(INCLUDE_FULL_CONTEXT_WINDOW or full_context),
        )
        if full_context and n_words not in windows:
            windows.append(n_words)
            windows = sorted(set(windows))
    print(f"Windows to generate: {windows}")
    if n_words in windows:
        print(f"Full context is included (window={n_words}).")
    print(f"Target Layers: {target_layers}")

    # Metadata
    all_embedding_paths = {}

    # Process Windows
    for win_size in windows:
        print(f"\nProcessing Window {win_size}...")

        paths = generate_embeddings_fast(
            window_size=win_size,
            full_input_ids=full_input_ids,
            starts=starts,
            ends=ends,
            n_words=n_words,
            model=model,
            tokenizer=tokenizer,
            layer_indices=target_layers,
            device=device,
            hidden_size=model.config.hidden_size,
            base_results_dir=BASE_RESULTS_DIR,
            skip_existing=skip_existing
        )
        all_embedding_paths[win_size] = paths

    # Save Metadata
    metadata = {
        "model": MODEL_NAME,
        "method": "fast_chunked_sliding_window_with_pos_ids",
        "word_embedding_mode": bool(WORD_EMBEDDING_MODE),
        "hidden_states_index_meaning": {
            # HuggingFace convention for Llama: hidden_states[0] is token embeddings output,
            # then hidden_states[i+1] is the output after transformer layer i.
            "0": "token_embedding_output",
            "1": "transformer_layer_0_output",
            "2": "transformer_layer_1_output",
        },
        "target_layers": target_layers,
        "context_windows": windows,
        "full_context_window": int(n_words) if int(n_words) in windows else None,
        "n_words": n_words,
        "embeddings": all_embedding_paths,
        "base_results_dir": str(BASE_RESULTS_DIR),
    }

    metadata_path = BASE_RESULTS_DIR / "generation_metadata_fast.json"
    with open(metadata_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)
    print(f"Saved metadata to {metadata_path}")
    print("\n--- Done ---")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--context-windows", type=str, default=None,
                        help="Comma-separated window sizes in words (default 1..20).")
    parser.add_argument("--layers", type=str, default=None,
                        help="Comma-separated hidden_states indices "
                             "(default 0,5,10,15,20,25,30).")
    parser.add_argument("--skip-existing", action="store_true", default=True)
    parser.add_argument("--full-context", action="store_true", default=False)
    args = parser.parse_args()

    if args.layers:
        TARGET_LAYERS = [int(x) for x in args.layers.split(",")]

    windows_arg = None
    if args.context_windows:
        windows_arg = [int(x) for x in args.context_windows.split(",")]

    main(windows_arg, args.skip_existing, args.full_context)




